In [2]:
import re
import sqlite3

import pandas as pd

In [2]:
df = pd.read_csv(
    "/mnt/data/workspace/bogor-agrisat/data/production-data/attributes/zonal-stats.csv"
)
df.head()

,count,min,max,sum,mean,stdev,timestamp,variable,hash
0,12.763496,0.062060,0.094948,0.999101,0.078278,0.007527,20260331T112509,gndvi,f698b891c432a8fc9aeebd8cfaca9c51
1,2.820084,0.063052,0.073774,0.187589,0.066519,0.002402,20260331T112509,gndvi,92eac953eef8b4ce4e0aac12f1df207f
2,61.633963,0.056255,0.139228,4.861641,0.078879,0.017409,20260331T112509,gndvi,60307db86871b782f5bc1d5d88a723b3
3,26.180419,0.064843,0.080024,1.875881,0.071652,0.003772,20260331T112509,gndvi,aa3f6bfc857119446857286da1ab42e2
4,10.753529,0.074132,0.124681,0.972006,0.090389,0.011163,20260331T112509,gndvi,c7c41c1b295fab2fc616f01fc4e7e0db

In [ ]:
dd = df.pivot_table(
    index=["timestamp", "hash"], columns=["variable"], values=["mean"]
).reset_index()
dd.columns = [x[0 if x[1] == "" else 1] for x in dd.columns]

dd.head()

,timestamp,hash,cire,gndvi,msavi,ndmi,ndre,ndvi,ndwi,wdrvi
0,20260103T063239,2926c1a6172afbf34fffae73661f98c7,0.014253,0.029418,0.047769,0.325830,0.009503,0.024478,-0.029418,-0.809922
1,20260103T063239,2b32ac7548cb5d0b38979860f56d409c,0.010743,0.029442,0.047769,0.304909,0.009980,0.024475,-0.029442,-0.809924
2,20260103T063239,60307db86871b782f5bc1d5d88a723b3,0.012703,0.029081,0.046326,0.310076,0.009245,0.023716,-0.029081,-0.810186
3,20260103T063239,92eac953eef8b4ce4e0aac12f1df207f,0.011574,0.029734,0.046063,0.309492,0.010942,0.023577,-0.029734,-0.810234
4,20260103T063239,991c7e0b1ed1e691e5d02b11aa2a52cc,0.014422,0.030182,0.051267,0.322045,0.011932,0.026319,-0.030182,-0.809287

In [5]:
ts = re.search(
    r"([0-9]{4})([0-9]{2})([0-9]{2})T([0-9]{2})([0-9]{2})([0-9]{2})", "20260103T063239"
)
ts

In [8]:
f"{ts.group(1)}-{ts.group(2)}-{ts.group(3)} {ts.group(4)}:{ts.group(5)}:{ts.group(6)}"

'2026-01-03 06:32:39'